name: Test & Lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      
      - name: Check formatting
        run: deno fmt --check
      
      - name: Lint
        run: deno lint
      
      
      - name: Type check Web
        run: deno task --cwd apps/web check
